# Exported from Render on 2024-07-18T10:57:21Z
services:
- type: web
  name: peitrak-1
  runtime: docker
  repo: https://github.com/Austin-rgb/actix-ecommerce
  plan: free
  region: oregon
  buildCommand: echo $GITHUB_TOKEN | docker login ghcr.io -u austin-rgb --password-stdin
  
  rootDir: .
version: "1"
