# Generated by Django 4.2.14 on 2024-07-13 08:10

from django.db import migrations, models
import django.db.models.deletion
import peitrak.models


class Migration(migrations.Migration):

    dependencies = [
        ('peitrak', '0002_deposit_pendingdeposit_pendingwithdrawal_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledtransaction',
            name='id',
            field=models.CharField(default=peitrak.models.transaction_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='completedtransaction',
            name='id',
            field=models.CharField(default=peitrak.models.transaction_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='id',
            field=models.CharField(default=peitrak.models.transaction_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rejectedtransaction',
            name='id',
            field=models.CharField(default=peitrak.models.transaction_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(default=peitrak.models.request_id, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peitrak.account')),
            ],
        ),
    ]
