# Generated by Django 4.2.14 on 2024-07-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import peitrak.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peitrak', '0003_alter_cancelledtransaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=peitrak.models.transaction_id, max_length=10, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('sent', models.BooleanField(default=False)),
                ('pin', models.IntegerField(default=peitrak.models.generate_pin)),
                ('received', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('received_on', models.DateTimeField(null=True)),
                ('cancelled_on', models.DateTimeField(null=True)),
                ('rejected_on', models.DateTimeField(null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transactions_received', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transactions_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='completedtransaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='completedtransaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rejectedtransaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='rejectedtransaction',
            name='source',
        ),
        migrations.DeleteModel(
            name='CancelledTransaction',
        ),
        migrations.DeleteModel(
            name='CompletedTransaction',
        ),
        migrations.DeleteModel(
            name='PendingTransaction',
        ),
        migrations.DeleteModel(
            name='RejectedTransaction',
        ),
    ]
